apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: weave-gitops
  namespace: wego-system
resources:
- app.yaml
- weave-gitops-gitops-deploy.yaml
- weave-gitops-gitops-source.yaml
