---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: wego-kind-cluster2-nginx2
  namespace: wego-system
spec:
  interval: 30s
  ref:
    branch: main
  secretRef:
    name: wego-kind-cluster2-nginx2
  url: ssh://git@github.com/jrryjcksn/nginx2.git

